### ISSUE TITLE
Add favicon to live.glidernet.org

### ISSUE THREAD

**Issue by dspreitz** [glidernet/ogn-live#15]
Hello,
can you add a favicon (https://en.wikipedia.org/wiki/Favicon) to live.glidernet.org?
I think the favicon used on the wiki would be good.

**Comment by clementallen** [comment]
Pull request #42 raised to add favicon

**Comment by snip** [comment]
https://github.com/glidernet/ogn-live/commit/2d38cd9eac7c3bc6579b89616b41fc5b83e420b0
