### ISSUE TITLE
Pls add airfield "Mönchsheide" (receiver "Heide") to FlightLog

### ISSUE THREAD

**Issue by vol907** [glidernet/ogn-live#26]
Could someone be so kind to add airfield "Mönchsheide" (receiver "Heide") to FlightLog. Parameters should be the following:

'Mönc'=> array('Mönchsheide',"l.rec='Heide' AND l.alt < 904 AND (l.lat BETWEEN 50.50675 AND 50.50931 ) AND (l.lon BETWEEN 7.2498 AND 7.2622)",204,''),

Thanks in advance!

Regards
David

**Comment by janhebnes** [comment]
It has been added on the 29th of april by cunimb 
line 163 'MONCH'=> array('Monchsheide',"l.rec='Monchshei' AND l.alt < 905 AND (l.lat BETWEEN 50.50462 AND 50.51491 ) AND (l.lon BETWEEN 7.24319 AND 7.26705)",205,''),
