### ISSUE TITLE
Please add Bicester Airfield to Flight Log List of Airfields

### ISSUE THREAD

**Issue by JulianBane** [glidernet/ogn-live#34]
Name: Bicester Airfield
ICAO Name: EGDD
Elevation AMSL: 259 ft / 79 m
Location: 51°54′58″N 1°08′07″W
Airfield Bounds: 
    Lat: 51.912 to 51.921
    Long: -1.139 to -1.122
BGA Turnpiont: BIC
Local Receiver: UKBIC

**Comment by clementallen** [comment]
@JulianBane Bicester airfield has been added.  Please see https://github.com/glidernet/ogn-live/blob/master/flightlog/aerolist.php#L37

I believe this issue can now be closed @cunimb ?

**Comment by JulianBane** [comment]
Hi Clem,

Can confirm it has. Right now at Lasham helping on an instructor course. The bar is calling me ..... ;-)

Julian
