### ISSUE TITLE
Please add EDMD to airfield list 

### ISSUE THREAD

**Issue by KirillNeduzhiy** [glidernet/ogn-live#38]
Hi cunimb,

could you please add the airfield EDMD into the aerolist? (also see my pull req)

Here's the string to add:

'EDMD'=> array('Dachau-Groebenried',"l.rec='EDMD' AND l.alt < 1190 AND (l.lat BETWEEN 48.2285 AND 48.2485 ) AND (l.lon BETWEEN 11.4262 AND 11.4462)",490,''),

Thanks in advance!

**Comment by clementallen** [comment]
@KirillNeduzhiy EDMD has been added.  Please see https://github.com/glidernet/ogn-live/blob/master/flightlog/aerolist.php#L74

@cunimb I believe this issue can now be closed
