### ISSUE TITLE
Please add airfield EDPD

### ISSUE THREAD

**Issue by dspreitz** [glidernet/ogn-live#39]
Can you pleas add the airfield EDPD to aerolist.php

Here are the dates of the airfield
'EDPD'=> array('Dingolfing',"l.rec='EDPD' AND l.alt < 1055 AND (l.lat BETWEEN 48.65 AND 48.66 ) AND (l.lon BETWEEN 12.49 AND 12.51)",355,''),

**Comment by clementallen** [comment]
@dspreitz EDPD has been added.  Please see https://github.com/glidernet/ogn-live/blob/master/flightlog/aerolist.php#L80

@cunimb this issue can now be closed

**Comment by dspreitz** [comment]
Thanks a Lot.

Am 6. September 2016 14:48:49 MESZ, schrieb Clement Allen <notifications@github.com>:
>@dspreitz EDPD has been added.  Please see
>https://github.com/glidernet/ogn-live/blob/master/flightlog/aerolist.php#L80
>
>@cunimb this issue can now be closed
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/glidernet/ogn-live/issues/39#issuecomment-244939432

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
