### ISSUE TITLE
Cross Origin Resource Sharing headers are missing

### ISSUE THREAD

**Issue by Turbo87** [glidernet/ogn-live#5]
`rec.php` and `lxml.php` are not returning any [CORS](http://en.wikipedia.org/wiki/Cross-origin_resource_sharing) headers, which makes it impossible to use the data on any other server/domain or use it locally for development.

Instructions for enabling CORS on nginx can be found e.g. [here](http://enable-cors.org/server_nginx.html)

**Comment by Turbo87** [comment]
It can actually be done even easier directly in the PHP script: http://enable-cors.org/server_php.html

**Comment by Turbo87** [comment]
some instructions on how to temporarily (!) disable CORS locally for development until this issue has been fixed: https://blog.nraboy.com/2014/08/bypass-cors-errors-testing-apis-locally/

**Comment by Turbo87** [comment]
@snip any news on this?

**Comment by snip** [comment]
The PHP solution seems to be the best one.
So Philoo, i think it is for you ;)

**Comment by cunimb** [comment]
Yes,
I'm busy these days.
I'm planning to do it this week-end.

Le 26/01/2015 16:49, Sebastien Chaumontet a écrit :
>
> The PHP solution seems to be the best one.
> So Philoo, i think it is for you ;)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/glidernet/ogn-live/issues/5#issuecomment-71481673>.
>



---
Ce courrier électronique ne contient aucun virus ou logiciel malveillant parce que la protection avast! Antivirus est active.
http://www.avast.com

**Comment by Turbo87** [comment]
@cunimb let me know if I can help in any way

**Comment by cunimb** [comment]
New headers have been added.
Tell me if it's ok.

**Comment by Turbo87** [comment]
@cunimb looks good, thanks
