### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by Turbo87** [glidernet/ogn-live#6]
The code/repository is essentially not usable by others without a comment on the license. Help on choosing a license is provided at e.g. http://choosealicense.com/

**Comment by Turbo87** [comment]
@snip any news on this?

**Comment by snip** [comment]
I think GPLv3 can be good for the project.
Anythought @Turbo87 @cunimb ?

**Comment by Turbo87** [comment]
I don't like the GPL in general that much anymore and would prefer a more permissive license like MIT or Apache... and as I've mentioned via mail already in this case you would need to use the even harder AGPL since you are offering a web service here. On the other hand given how the Flarm company behaved again lately and the small "market" that this software is addressing, it might be a good idea to indeed use some form of the GPL license here.

**Comment by snip** [comment]
ok i'm convinced by AGPL.
@cunimb ?

**Comment by cunimb** [comment]
That sounds good, let's go :-)
