### ISSUE TITLE
Offline glider labels shifted north

### ISSUE THREAD

**Issue by snip** [glidernet/ogn-live#79]
Hi,

since the introduction of "Altitude stick" feature, when we uncheck "Ignore Offline", all offline labels are shifted to north as if the "Altitude stick" was checked (bit it is not checked).

So if you right click on the label loading the history track, you see the offset as on folwing picture:

![image](https://user-images.githubusercontent.com/466133/35183539-48711566-fde8-11e7-9e53-8795c381c986.png)

There is no issue with online gliders.

Thanks

**Comment by nbonniere** [comment]
Yes, there is a bug. By default, the stick is enabled and the update is only done when a new position is received, but with offline gliders, no new position is received, so no update.
I have a fix, but pull-request #75 must be done beforehand.

**Comment by snip** [comment]
Issue seems to be resolved.
Since migration to OSM?
![image](https://user-images.githubusercontent.com/466133/48738296-d92ddb00-ec50-11e8-82fb-ae11d6f48dbc.png)
