### ISSUE TITLE
HTTPS not supported

### ISSUE THREAD

**Issue by clementallen** [glidernet/ogn-live#89]
live.glidernet.org does not load over HTTPS.  This should be easy to setup using Lets Encrypt just like the glidernet.org homepage uses

**Comment by snip** [comment]
Hi,

it is easy to setup yes, but not to maintain.
Why do you need live to be available over HTTPS protocol?
Do you see any confidential information which need to be secured?

**Comment by clementallen** [comment]
The reason is not because confidential information is being passed, but because the API cannot be used on other HTTPS pages as the browser blocks non-HTTPS requests.

**Comment by snip** [comment]
Understood.
live.glidernet.org is now available in https.
Not all interface as some code need to be updated.

But this should suite your need.

Just for my information, can you share for which site you are using it?

See u
--
Seb

**Comment by clementallen** [comment]
Wonderful, thank you @snip!  The site is not in a ready state yet but I'll try and share it when completed
